### ISSUE TITLE
主题安装不成功

### ISSUE THREAD

**Issue by Rick630** [littlewin-wang/hexo-theme-casual#3]
`extends partial/layout block container include mixins/post +posts() block pagination include mixins/paginator +home() block copyright include partial/copyright`

**Comment by littlewin-wang** [comment]
Sorry, 可以仔细贴下出错的log么
我在空白机器上又试了下，貌似没问题啊

**Comment by Rick630** [comment]
抱歉没说清楚，hexo g都没问题，只是打开主页就会显示这段错误

extends partial/layout block container include mixins/post +posts() block pagination include mixins/paginator +home() block copyright include partial/copyright

**Comment by littlewin-wang** [comment]
有无做这一步
```
//Add dependencies
$ npm install --save hexo-renderer-jade hexo-renderer-scss hexo-generator-feed hexo-generator-sitemap hexo-browsersync hexo-generator-archive
```

**Comment by Rick630** [comment]
![image](https://cloud.githubusercontent.com/assets/11673596/22870237/9d1f9b7e-f1e0-11e6-9c57-62774d296ead.png)
似乎还是不行

`kkk:blog huangzh$ hexo version
hexo: 3.1.1
os: Darwin 15.6.0 darwin x64
http_parser: 2.5.0
node: 4.1.2
v8: 4.5.103.35
uv: 1.7.5
zlib: 1.2.8
ares: 1.10.1-DEV
modules: 46
openssl: 1.0.2d
`

**Comment by ChasonMei** [comment]
同样的问题，不成功。应该是这里有问题吧。

```
$ npm install --save hexo-renderer-jade hexo-renderer-scss hexo-generator-feed hexo-generator-sitemap hexo-browsersync hexo-generator-archive
npm WARN deprecated node-uuid@1.4.7: use uuid module instead
npm WARN deprecated jade@1.11.0: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated transformers@2.1.0: Deprecated, use jstransformer
npm WARN prefer global node-gyp@3.5.0 should be installed with -g

> node-sass@3.13.1 install E:\hexo_chason_blog\blog\node_modules\node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v3.13.1/win32-ia32-48_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v3.13.1/win32-ia32-48_binding.node":

ESOCKETTIMEDOUT

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> node-sass@3.13.1 postinstall E:\hexo_chason_blog\blog\node_modules\node-sass
> node scripts/build.js

Binary found at E:\hexo_chason_blog\blog\node_modules\node-sass\vendor\win32-ia32-48\binding.node
Testing binary
Binary has a problem: Error: %1 is not a valid Win32 application.
\\?\E:\hexo_chason_blog\blog\node_modules\node-sass\vendor\win32-ia32-48\binding.node
    at Error (native)
    at Object.Module._extensions..node (module.js:597:18)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at module.exports (E:\hexo_chason_blog\blog\node_modules\node-sass\lib\binding.js:19:10)
    at Object.<anonymous> (E:\hexo_chason_blog\blog\node_modules\node-sass\lib\index.js:14:35)
    at Module._compile (module.js:570:32)
Building the binary locally
Building: D:\Program Files\nodejs\node.exe E:\hexo_chason_blog\blog\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ 'D:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'E:\\hexo_chason_blog\\blog\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.5.0
gyp info using node@6.9.5 | win32 | ia32
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (E:\hexo_chason_blog\blog\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (E:\hexo_chason_blog\blog\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (E:\hexo_chason_blog\blog\node_modules\which\which.js:80:29)
gyp verb `which` failed     at E:\hexo_chason_blog\blog\node_modules\which\which.js:89:16
gyp verb `which` failed     at E:\hexo_chason_blog\blog\node_modules\isexe\index.js:44:5
gyp verb `which` failed     at E:\hexo_chason_blog\blog\node_modules\isexe\windows.js:29:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:123:15)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (E:\hexo_chason_blog\blog\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (E:\hexo_chason_blog\blog\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (E:\hexo_chason_blog\blog\node_modules\which\which.js:80:29)
gyp verb `which` failed     at E:\hexo_chason_blog\blog\node_modules\which\which.js:89:16
gyp verb `which` failed     at E:\hexo_chason_blog\blog\node_modules\isexe\index.js:44:5
gyp verb `which` failed     at E:\hexo_chason_blog\blog\node_modules\isexe\windows.js:29:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:123:15) code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` failed Error: not found: python
gyp verb `which` failed     at getNotFoundError (E:\hexo_chason_blog\blog\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (E:\hexo_chason_blog\blog\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (E:\hexo_chason_blog\blog\node_modules\which\which.js:80:29)
gyp verb `which` failed     at E:\hexo_chason_blog\blog\node_modules\which\which.js:89:16
gyp verb `which` failed     at E:\hexo_chason_blog\blog\node_modules\isexe\index.js:44:5
gyp verb `which` failed     at E:\hexo_chason_blog\blog\node_modules\isexe\windows.js:29:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:123:15)
gyp verb `which` failed  python { Error: not found: python
gyp verb `which` failed     at getNotFoundError (E:\hexo_chason_blog\blog\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (E:\hexo_chason_blog\blog\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (E:\hexo_chason_blog\blog\node_modules\which\which.js:80:29)
gyp verb `which` failed     at E:\hexo_chason_blog\blog\node_modules\which\which.js:89:16
gyp verb `which` failed     at E:\hexo_chason_blog\blog\node_modules\isexe\index.js:44:5
gyp verb `which` failed     at E:\hexo_chason_blog\blog\node_modules\isexe\windows.js:29:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:123:15) code: 'ENOENT' }
gyp verb could not find "python". checking python launcher
gyp verb could not find "python". guessing location
gyp verb ensuring that file exists: C:\Python27\python.exe
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at Object.failNoPython (E:\hexo_chason_blog\blog\node_modules\node-gyp\lib\configure.js:454:19)
gyp ERR! stack     at Object.<anonymous> (E:\hexo_chason_blog\blog\node_modules\node-gyp\lib\configure.js:480:16)
gyp ERR! stack     at E:\hexo_chason_blog\blog\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:123:15)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "D:\\Program Files\\nodejs\\node.exe" "E:\\hexo_chason_blog\\blog\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd E:\hexo_chason_blog\blog\node_modules\node-sass
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok
Build failed with error code: 1
hexo-site@0.0.0 E:\hexo_chason_blog\blog
+-- hexo-browsersync@0.2.0
+-- hexo-generator-archive@0.1.4
+-- hexo-generator-feed@1.2.0
+-- hexo-generator-sitemap@1.1.2
`-- hexo-renderer-jade@0.3.0

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.17: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"ia32"})
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "hexo-renderer-jade" "hexo-renderer-scss" "hexo-generator-feed" "hexo-generator-sitemap" "hexo-browsersync" "hexo-generator-archive"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! node-sass@3.13.1 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@3.13.1 postinstall script 'node scripts/build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\hexo_chason_blog\blog\npm-debug.log

```

**Comment by littlewin-wang** [comment]
楼上的童鞋是没装python吧

**Comment by littlewin-wang** [comment]
@Rick630 你的错误应该是jade模板没有被解析，按道理应该是hexo-renderer-jade没装好

**Comment by Rick630** [comment]
@littlewin-wang 

`//Add dependencies
$ npm install --save hexo-renderer-jade hexo-renderer-scss hexo-generator-feed hexo-generator-sitemap hexo-browsersync hexo-generator-archive
`

再跑了一次这个，就好了

**Comment by Rick630** [comment]
@littlewin-wang 

想问一下tags页面我的怎么和你的不一样呢

![image](https://cloud.githubusercontent.com/assets/11673596/22924320/9cc64934-f2df-11e6-986c-1f35ad47371b.png)

**Comment by littlewin-wang** [comment]
/source/tags/index.md
```
---
title: tags
layout: "tags"
---
```
这个设置好了么

**Comment by Rick630** [comment]
@littlewin-wang 

感谢耐心解答
